Repository DeveloperAcademy-POSTECH/MacC-Team15-Ampersand, pull requests merged in 2023-11, with the labels that each got.

#66 [feat][#61] PlanBoardView와 ProjectBoardView의 Hover, FocusGroup TCA구조의 코드 작성
  gridy.xcodeproj/project.pbxproj
  gridy/Resources/Assets.xcassets/PlanBoardColors/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/horizontalLine.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/horizontalSection.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/index.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/indexHovered.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/lineArea.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/list.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/listHovered.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/listItem.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/planBoardBorder.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/rightToolBar.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/topToolBar.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/topToolItem.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/verticalLine.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/verticalLineWeek.colorset/Contents.json
  gridy/Resources/Assets.xcassets/PlanBoardColors/weekend.colorset/Contents.json
  gridy/Resources/Assets.xcassets/SystemColors/tabLabelInactive.colorset/Contents.json
  gridy/Sources/Deprecated/ProjectBoardViewDeprecated.swift
  gridy/Sources/Extensions/Color+Extension.swift
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Presentations/Authentication/AuthenticationView.swift
  gridy/Sources/Presentations/Common/Components.swift
  gridy/Sources/Presentations/Common/TabBarView.swift
  gridy/Sources/Presentations/PlanBoard/CalendarView.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/PlanBoard/RightToolBarView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemEmptyView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
  gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature

#71 [feat][#69] view구조 TCA 전환
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/ContentView.swift
  gridy/Sources/Deprecated/AuthenticationViewDeprecated.swift
  gridy/Sources/Deprecated/ProjectBoardMainViewDeprecated.swift
  gridy/Sources/Deprecated/ProjectCreationViewDeprecated.swift
  gridy/Sources/Deprecated/ProjectEditViewDeprecated.swift
  gridy/Sources/Deprecated/ProjectItemViewDeprecated.swift
  gridy/Sources/Deprecated/ProjectSideItemViewDeprecated.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Common/AuthenticationView.swift
  gridy/Sources/Presentations/Common/TabBarView.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
  gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
Labels: ✨ feature

#74 [refactor][#54] delete model lane
  .swiftlint.yml
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/Feedback.swift
  gridy/Sources/Models/Lane.swift
  gridy/Sources/Models/Notice.swift
  gridy/Sources/Models/Plan.swift
  gridy/Sources/Models/PlanType.swift
  gridy/Sources/Models/Project.swift
  gridy/Sources/Models/User.swift
  gridy/Sources/Network/APIClient.swift
  gridy/Sources/Network/APIError.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Network/FirestoreService.swift
  gridy/Sources/Network/ImageUploader.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Authentication/SignInWithAppleButtonView.swift
  gridy/Sources/Presentations/Common/TabBarView.swift
  gridy/Sources/Presentations/PlanBoard/CalendarView.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LayerControlArea/LayerControlAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemEmptyView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
  gridy/Sources/Presentations/PlanBoard/tempView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
  gridy/Sources/Utils/Utils.swift
Labels: 🐛 bug, ✨ feature, 🧹 chore, 🚧 refactoring

#82 [feat][#78] 플랜보드 스토어 분리
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/Date+Extension.swift
  gridy/Sources/Models/Plan.swift
  gridy/Sources/Network/ImageUploader.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Common/TabBarView.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LayerControlArea/LayerControlAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemEmptyView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
Labels: 🚑 HOTFIX, 🐛 bug, ✨ feature, 🧹 chore, 🚧 refactoring

#85 [feat][#72] listArea to TCA
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/Plan.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarAreaView.swift
Labels: ✨ feature, 🧹 chore

#87 [feat][#83] Schedule CRUD
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Models/Schedule.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Network/FirestoreService.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
Labels: ✨ feature

#89 [feat][#78] 실제데이터에 따라 row에 맞춰 띄우기, update & delete plan on line
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/SelectedDateRange.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
Labels: 🐛 bug, ✨ feature, 🚧 refactoring

#93 [feat][#88] ScheduleArea View CRUD
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/Schedule.swift
  gridy/Sources/Models/SelectedScheduleRange.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
Labels: ✨ feature, 🚧 refactoring

#94 [feat][#72] listArea Action and View to TCA
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/SelectedGridRange.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
Labels: ✨ feature, 🧹 chore, 🚧 refactoring

#90 [feat][#86] WindowButton과 TabBarView 맞추기
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/ContentView.swift
  gridy/Sources/Presentations/Common/TabBarView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature
