Repository DeveloperAcademy-POSTECH/MacC-Team15-Ampersand, pull requests merged in 2023-10, with the labels that each got.

#22 [feat][#21] 그리드 만들고 드래그 기능 추가
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaRoyceView.swift
Labels: ✨ feature

#23 [feat][#11] Sign in with Apple
  .gitignore
  .swiftlint.yml
  Gemfile
  Gemfile.lock
  README.md
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  gridy.xcodeproj/project.pbxproj
  gridy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gridy/Resources/Assets.xcassets/Logo/Contents.json
  gridy/Resources/Assets.xcassets/Logo/gridBackground.imageset/Contents.json
  gridy/Resources/Assets.xcassets/Logo/gridBackground.imageset/gridBackground.png
  gridy/Resources/Assets.xcassets/Logo/gridBackground.imageset/gridBackground@2x.png
  gridy/Resources/Assets.xcassets/Logo/gridBackground.imageset/gridBackground@3x.png
  gridy/Resources/Assets.xcassets/Logo/gridy-logo.imageset/Contents.json
  gridy/Resources/Assets.xcassets/Logo/gridy-logo.imageset/gridy-logo.png
  gridy/Resources/Assets.xcassets/Logo/gridy-logo.imageset/gridy-logo@2x.png
  gridy/Resources/Assets.xcassets/Logo/gridy-logo.imageset/gridy-logo@3x.png
  gridy/Resources/gridy.entitlements
  gridy/Sources/ContentView.swift
  gridy/Sources/Extensions/DependencyValues+Extension.swift
  gridy/Sources/Extensions/String+Extension.swift
  gridy/Sources/Models/User.swift
  gridy/Sources/Network/APIClient.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Authentication/AuthenticationView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature, 🧹 chore

#26 Feat/24 timeaxisview
  gridy.xcodeproj/project.pbxproj
  gridy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  gridy/Sources/Extensions/Date+Extension.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/ScrollDatePickerView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/DayGridView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutContentView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature

#29 [feat][#12] 프로젝트에 대한 crud api 작업
  .gitignore
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/ContentView.swift
  gridy/Sources/Extensions/DependencyValues+Extension.swift
  gridy/Sources/Models/Project.swift
  gridy/Sources/Network/APIClient.swift
  gridy/Sources/Network/APIError.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Network/NetworkProtocol.swift
  gridy/Sources/Network/NetworkService.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Authentication/AuthenticationView.swift
  gridy/Sources/Presentations/Authentication/SignInWithAppleButtonView.swift
  gridy/Sources/Presentations/Common/BackgroundView.swift
  gridy/Sources/Presentations/PlanBoard/PlanItem.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature, 🧹 chore, 🚧 refactoring

#39 [feat][#33] plan crud api
  gridy.xcodeproj/project.pbxproj
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy128.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy16.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy256 1.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy256.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy32 1.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy32.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy512 1.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy512.png
  gridy/Resources/Assets.xcassets/AppIcon.appiconset/gridy64.png
  gridy/Sources/Extensions/Color+Extension.swift
  gridy/Sources/Extensions/DependencyValues+Extension.swift
  gridy/Sources/Models/Lane.swift
  gridy/Sources/Models/Plan.swift
  gridy/Sources/Models/PlanType.swift
  gridy/Sources/Models/Project.swift
  gridy/Sources/Network/APIError.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/Authentication/AuthenticationView.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardSideView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectCreationView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
Labels: ✨ feature

#45 43 feat linearea에 store를 연결하여 plan구조체를 생성합니다
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Extensions/Date+Extension.swift
  gridy/Sources/Models/Plan.swift
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleArea/ScheduleAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutContentView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardSideView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectCreationView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectEditView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
Labels: 🐛 bug, ✨ feature, 🧹 chore, 🚧 refactoring

#50 [feat][#32] listArea 구현
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Presentations/Authentication/Authentication.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/BlackPinkInYourArea/BlackPinkInYourAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/LargeTaskElementView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/LeftSmallTaskElementView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemEmptyView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/RightSmallTaskElementView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleArea/ScheduleAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutContentView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardMainView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectCreationView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItem.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
  gridy/Sources/gridyApp.swift
Labels: ✨ feature

#52 [feat][#51] layerControlArea 추가
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LayerControlArea/LayerControlAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineIndexArea/LineIndexAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleArea/ScheduleAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleIndexArea/ScheduleIndexAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutContentView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
Labels: ✨ feature

#53 [feat][#32] listArea createPlan 붙이기
  gridy.xcodeproj/project.pbxproj
  gridy/Sources/Network/APIService.swift
  gridy/Sources/Network/FirestoreService.swift
  gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemEmptyView.swift
  gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectBoardSideView.swift
  gridy/Sources/Presentations/ProjectBoard/ProjectSideItemView.swift
Labels: ✨ feature
